owner: BapRx
repo: upptime
assignees:
  - BapRx

sites:
  - name: Gitlab Pages
    url: https://baprx.gitlab.io/qigong-tuina-sallanches
  - name: Cloud Run
    url: https://www.qigong-tuina-sallanches.fr

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: dark
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
